# Generated by Django 5.0.4 on 2024-05-06 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_remove_task_created_at_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='todo_app.customuser'),
            preserve_default=False,
        ),
    ]
